# Do not change version. 
#This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20  
  pre_build:
    commands:
      - echo Install hugo
      - sudo dnf install hugo
      - hugo
      - echo Authen ECR
      - $(aws ecr get-login-password | docker login --username AWS --password-stdin)
      - REPOSITORY_URI=992382856114.dkr.ecr.us-east-1.amazonaws.com/ws002
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPO_URI:latest
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:IMAGE_TAG

